### ISSUE TITLE
Checklists outside the main comment

### ISSUE THREAD

**Issue by rubendinho** [mheap/require-checklist-action#20]
We often add one-off todos or checklists in reviews or other comments in the PR. 

Is it possible to have those fail the check?

**Comment by mheap** [comment]
Checklists in reviews are not currently supported, but checklists in comments should work fine https://github.com/mheap/require-checklist-action/blob/master/index.js#L15-L21

**Comment by NiallBegley** [comment]
I'm having a problem that is maybe related to this and maybe someone can help me out.  I want to create a workflow that makes a comment with a checklist on a newly opened PR reminding developers to go and update documentation and fail status checks until the developer acknowledges the checklist.  Here is my workflow:

````
name: 'PR Tasks Completed Check'
on: 
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited, deleted]
  issue_comment:
    types: [created, edited, deleted]
jobs:
  review-checklist:
    name: Make documentation comment on PR
    runs-on: ubuntu-latest
    steps:
      - name: "Make comment (if necessary)"
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Review Checklist
            - [ ] Documentation updated`,
            })
  require_checklist_c:
    name: "Require Checklist"
    runs-on: ubuntu-latest
    needs: [review-checklist]
    steps:
      - uses: mheap/require-checklist-action@v1
        with:
          requireChecklist: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The problem I'm having is that even though `require-checklist-action` runs fine and fails the status check appropriately after the PR is opened and the documentation comment is made, when it runs as the result of `issue_comment` being run after the person checks the box, I can see the workflow running again on the Actions tab but the status check on the PR itself remains in the failed state.  Is that something wrong on my end or something on the `require-checklist-action` side?

**Comment by mheap** [comment]
I finally got around to testing this out. Unfortunately it's a limitation of GitHub Actions.

The `issue_comment` event can't clear the build check for `pull_request`. Only the [following events ](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) can trigger a re-check:

- assigned
- unassigned
- labeled
- unlabeled
- opened
- edited
- closed
- reopened
- synchronize
- converted_to_draft
- ready_for_review
- locked
- unlocked
- review_requested
- review_request_removed
- auto_merge_enabled
- auto_merge_disabled
