### ISSUE TITLE
Markdown Comments Fail Check

### ISSUE THREAD

**Issue by mike-stewart** [mheap/require-checklist-action#40]
I have an example like this in my pull_request_template.md:

```
- [x] task 1
- [x] task 2
<!-- Optional Tasks
- [ ] task 3
-->
```

Given that this task is usually commented out, it is not visible in the pull request body, but it still causes this action to error like:
```
Error: The following items are not marked as completed: task 3
```

Would it be possible to excluded tasks that are not visible?

**Comment by mheap** [comment]
This is now usable in `@v2`

**Comment by mike-stewart** [comment]
@mheap Thanks, works great! 🎉
